using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string ChucVu = @"ChucVu";
        
		public static readonly string DiemDanh = @"DiemDanh";
        
		public static readonly string DotKiemTra = @"DotKiemTra";
        
		public static readonly string DotTuyenSinh = @"DotTuyenSinh";
        
		public static readonly string GiaoVien = @"GiaoVien";
        
		public static readonly string HocPhi = @"HocPhi";
        
		public static readonly string HocVien = @"HocVien";
        
		public static readonly string KetQuaHocTap = @"KetQuaHocTap";
        
		public static readonly string KetQuaTuyenSinh = @"KetQuaTuyenSinh";
        
		public static readonly string KhoaHoc = @"KhoaHoc";
        
		public static readonly string LichGiangDay = @"LichGiangDay";
        
		public static readonly string Lop = @"Lop";
        
		public static readonly string NguoiDungADM = @"NguoiDungADM";
        
		public static readonly string NguoiDungGiaoVien = @"NguoiDungGiaoVien";
        
		public static readonly string NguoiDungHocVien = @"NguoiDungHocVien";
        
		public static readonly string NhanVien = @"NhanVien";
        
		public static readonly string NhapHoc = @"NhapHoc";
        
		public static readonly string PhongHoc = @"PhongHoc";
        
		public static readonly string ThongBaoGiaoVien = @"ThongBaoGiaoVien";
        
		public static readonly string ThongBaoLop = @"ThongBaoLop";
        
		public static readonly string ThuChi = @"ThuChi";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table ChucVu
		{
            get { return DataService.GetSchema("ChucVu", "QLSUN"); }
		}
        
		public static TableSchema.Table DiemDanh
		{
            get { return DataService.GetSchema("DiemDanh", "QLSUN"); }
		}
        
		public static TableSchema.Table DotKiemTra
		{
            get { return DataService.GetSchema("DotKiemTra", "QLSUN"); }
		}
        
		public static TableSchema.Table DotTuyenSinh
		{
            get { return DataService.GetSchema("DotTuyenSinh", "QLSUN"); }
		}
        
		public static TableSchema.Table GiaoVien
		{
            get { return DataService.GetSchema("GiaoVien", "QLSUN"); }
		}
        
		public static TableSchema.Table HocPhi
		{
            get { return DataService.GetSchema("HocPhi", "QLSUN"); }
		}
        
		public static TableSchema.Table HocVien
		{
            get { return DataService.GetSchema("HocVien", "QLSUN"); }
		}
        
		public static TableSchema.Table KetQuaHocTap
		{
            get { return DataService.GetSchema("KetQuaHocTap", "QLSUN"); }
		}
        
		public static TableSchema.Table KetQuaTuyenSinh
		{
            get { return DataService.GetSchema("KetQuaTuyenSinh", "QLSUN"); }
		}
        
		public static TableSchema.Table KhoaHoc
		{
            get { return DataService.GetSchema("KhoaHoc", "QLSUN"); }
		}
        
		public static TableSchema.Table LichGiangDay
		{
            get { return DataService.GetSchema("LichGiangDay", "QLSUN"); }
		}
        
		public static TableSchema.Table Lop
		{
            get { return DataService.GetSchema("Lop", "QLSUN"); }
		}
        
		public static TableSchema.Table NguoiDungADM
		{
            get { return DataService.GetSchema("NguoiDungADM", "QLSUN"); }
		}
        
		public static TableSchema.Table NguoiDungGiaoVien
		{
            get { return DataService.GetSchema("NguoiDungGiaoVien", "QLSUN"); }
		}
        
		public static TableSchema.Table NguoiDungHocVien
		{
            get { return DataService.GetSchema("NguoiDungHocVien", "QLSUN"); }
		}
        
		public static TableSchema.Table NhanVien
		{
            get { return DataService.GetSchema("NhanVien", "QLSUN"); }
		}
        
		public static TableSchema.Table NhapHoc
		{
            get { return DataService.GetSchema("NhapHoc", "QLSUN"); }
		}
        
		public static TableSchema.Table PhongHoc
		{
            get { return DataService.GetSchema("PhongHoc", "QLSUN"); }
		}
        
		public static TableSchema.Table ThongBaoGiaoVien
		{
            get { return DataService.GetSchema("ThongBaoGiaoVien", "QLSUN"); }
		}
        
		public static TableSchema.Table ThongBaoLop
		{
            get { return DataService.GetSchema("ThongBaoLop", "QLSUN"); }
		}
        
		public static TableSchema.Table ThuChi
		{
            get { return DataService.GetSchema("ThuChi", "QLSUN"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["QLSUN"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	}
    #endregion
    
}
#region Databases
public partial struct Databases 
{
	
	public static readonly string QLSUN = @"QLSUN";
    
}
#endregion