using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    /// <summary>
    /// Controller class for ChucVu
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ChucVuController
    {
        // Preload our schema..
        ChucVu thisSchemaLoad = new ChucVu();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ChucVuCollection FetchAll()
        {
            ChucVuCollection coll = new ChucVuCollection();
            Query qry = new Query(ChucVu.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ChucVuCollection FetchByID(object IdChucVu)
        {
            ChucVuCollection coll = new ChucVuCollection().Where("IdChucVu", IdChucVu).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ChucVuCollection FetchByQuery(Query qry)
        {
            ChucVuCollection coll = new ChucVuCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdChucVu)
        {
            return (ChucVu.Delete(IdChucVu) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdChucVu)
        {
            return (ChucVu.Destroy(IdChucVu) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public ChucVu Insert(ChucVu item)
	    {
		   
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public ChucVu Update(ChucVu item)
	    {
		   
				
	        item.Save(UserName);
            return item;
	    }
    }
}
