using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
	/// <summary>
	/// Strongly-typed collection for the ChucVu class.
	/// </summary>
    [Serializable]
	public partial class ChucVuCollection : ActiveList<ChucVu, ChucVuCollection>
	{	   
		public ChucVuCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>ChucVuCollection</returns>
		public ChucVuCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                ChucVu o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the ChucVu table.
	/// </summary>
	[Serializable]
	public partial class ChucVu : ActiveRecord<ChucVu>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public ChucVu()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public ChucVu(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public ChucVu(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public ChucVu(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("ChucVu", TableType.Table, DataService.GetInstance("QLSUN"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdChucVu = new TableSchema.TableColumn(schema);
				colvarIdChucVu.ColumnName = "IdChucVu";
				colvarIdChucVu.DataType = DbType.Guid;
				colvarIdChucVu.MaxLength = 0;
				colvarIdChucVu.AutoIncrement = false;
				colvarIdChucVu.IsNullable = false;
				colvarIdChucVu.IsPrimaryKey = true;
				colvarIdChucVu.IsForeignKey = false;
				colvarIdChucVu.IsReadOnly = false;
				
						colvarIdChucVu.DefaultSetting = @"(newid())";
				colvarIdChucVu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdChucVu);
				
				TableSchema.TableColumn colvarTenChucVu = new TableSchema.TableColumn(schema);
				colvarTenChucVu.ColumnName = "TenChucVu";
				colvarTenChucVu.DataType = DbType.String;
				colvarTenChucVu.MaxLength = 50;
				colvarTenChucVu.AutoIncrement = false;
				colvarTenChucVu.IsNullable = false;
				colvarTenChucVu.IsPrimaryKey = false;
				colvarTenChucVu.IsForeignKey = false;
				colvarTenChucVu.IsReadOnly = false;
				colvarTenChucVu.DefaultSetting = @"";
				colvarTenChucVu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenChucVu);
				
				TableSchema.TableColumn colvarLuongThang = new TableSchema.TableColumn(schema);
				colvarLuongThang.ColumnName = "LuongThang";
				colvarLuongThang.DataType = DbType.Decimal;
				colvarLuongThang.MaxLength = 0;
				colvarLuongThang.AutoIncrement = false;
				colvarLuongThang.IsNullable = true;
				colvarLuongThang.IsPrimaryKey = false;
				colvarLuongThang.IsForeignKey = false;
				colvarLuongThang.IsReadOnly = false;
				colvarLuongThang.DefaultSetting = @"";
				colvarLuongThang.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLuongThang);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["QLSUN"].AddSchema("ChucVu",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdChucVu")]
		[Bindable(true)]
		public Guid IdChucVu 
		{
			get { return GetColumnValue<Guid>(Columns.IdChucVu); }
			set { SetColumnValue(Columns.IdChucVu, value); }
		}
		  
		[XmlAttribute("TenChucVu")]
		[Bindable(true)]
		public string TenChucVu 
		{
			get { return GetColumnValue<string>(Columns.TenChucVu); }
			set { SetColumnValue(Columns.TenChucVu, value); }
		}
		  
		[XmlAttribute("LuongThang")]
		[Bindable(true)]
		public decimal? LuongThang 
		{
			get { return GetColumnValue<decimal?>(Columns.LuongThang); }
			set { SetColumnValue(Columns.LuongThang, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		public Public.NhanVienCollection NhanVienRecords()
		{
			return new Public.NhanVienCollection().Where(NhanVien.Columns.IdChucVu, IdChucVu).Load();
		}
		#endregion
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdChucVu,string varTenChucVu,decimal? varLuongThang)
		{
			ChucVu item = new ChucVu();
			
			item.IdChucVu = varIdChucVu;
			
			item.TenChucVu = varTenChucVu;
			
			item.LuongThang = varLuongThang;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdChucVu,string varTenChucVu,decimal? varLuongThang)
		{
			ChucVu item = new ChucVu();
			
				item.IdChucVu = varIdChucVu;
			
				item.TenChucVu = varTenChucVu;
			
				item.LuongThang = varLuongThang;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdChucVuColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TenChucVuColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn LuongThangColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdChucVu = @"IdChucVu";
			 public static string TenChucVu = @"TenChucVu";
			 public static string LuongThang = @"LuongThang";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
}
        #endregion
	}
}
