using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
	/// <summary>
	/// Strongly-typed collection for the DiemDanh class.
	/// </summary>
    [Serializable]
	public partial class DiemDanhCollection : ActiveList<DiemDanh, DiemDanhCollection>
	{	   
		public DiemDanhCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>DiemDanhCollection</returns>
		public DiemDanhCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                DiemDanh o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the DiemDanh table.
	/// </summary>
	[Serializable]
	public partial class DiemDanh : ActiveRecord<DiemDanh>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public DiemDanh()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public DiemDanh(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public DiemDanh(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public DiemDanh(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("DiemDanh", TableType.Table, DataService.GetInstance("QLSUN"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				
						colvarId.DefaultSetting = @"(newid())";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarIdLichGiangDay = new TableSchema.TableColumn(schema);
				colvarIdLichGiangDay.ColumnName = "IdLichGiangDay";
				colvarIdLichGiangDay.DataType = DbType.Guid;
				colvarIdLichGiangDay.MaxLength = 0;
				colvarIdLichGiangDay.AutoIncrement = false;
				colvarIdLichGiangDay.IsNullable = false;
				colvarIdLichGiangDay.IsPrimaryKey = false;
				colvarIdLichGiangDay.IsForeignKey = true;
				colvarIdLichGiangDay.IsReadOnly = false;
				colvarIdLichGiangDay.DefaultSetting = @"";
				
					colvarIdLichGiangDay.ForeignKeyTableName = "LichGiangDay";
				schema.Columns.Add(colvarIdLichGiangDay);
				
				TableSchema.TableColumn colvarIdNhapHoc = new TableSchema.TableColumn(schema);
				colvarIdNhapHoc.ColumnName = "IdNhapHoc";
				colvarIdNhapHoc.DataType = DbType.Guid;
				colvarIdNhapHoc.MaxLength = 0;
				colvarIdNhapHoc.AutoIncrement = false;
				colvarIdNhapHoc.IsNullable = false;
				colvarIdNhapHoc.IsPrimaryKey = false;
				colvarIdNhapHoc.IsForeignKey = true;
				colvarIdNhapHoc.IsReadOnly = false;
				colvarIdNhapHoc.DefaultSetting = @"";
				
					colvarIdNhapHoc.ForeignKeyTableName = "NhapHoc";
				schema.Columns.Add(colvarIdNhapHoc);
				
				TableSchema.TableColumn colvarTrangThai = new TableSchema.TableColumn(schema);
				colvarTrangThai.ColumnName = "TrangThai";
				colvarTrangThai.DataType = DbType.String;
				colvarTrangThai.MaxLength = 20;
				colvarTrangThai.AutoIncrement = false;
				colvarTrangThai.IsNullable = true;
				colvarTrangThai.IsPrimaryKey = false;
				colvarTrangThai.IsForeignKey = false;
				colvarTrangThai.IsReadOnly = false;
				colvarTrangThai.DefaultSetting = @"";
				colvarTrangThai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrangThai);
				
				TableSchema.TableColumn colvarGhiChu = new TableSchema.TableColumn(schema);
				colvarGhiChu.ColumnName = "GhiChu";
				colvarGhiChu.DataType = DbType.String;
				colvarGhiChu.MaxLength = 1073741823;
				colvarGhiChu.AutoIncrement = false;
				colvarGhiChu.IsNullable = true;
				colvarGhiChu.IsPrimaryKey = false;
				colvarGhiChu.IsForeignKey = false;
				colvarGhiChu.IsReadOnly = false;
				colvarGhiChu.DefaultSetting = @"";
				colvarGhiChu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGhiChu);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["QLSUN"].AddSchema("DiemDanh",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("IdLichGiangDay")]
		[Bindable(true)]
		public Guid IdLichGiangDay 
		{
			get { return GetColumnValue<Guid>(Columns.IdLichGiangDay); }
			set { SetColumnValue(Columns.IdLichGiangDay, value); }
		}
		  
		[XmlAttribute("IdNhapHoc")]
		[Bindable(true)]
		public Guid IdNhapHoc 
		{
			get { return GetColumnValue<Guid>(Columns.IdNhapHoc); }
			set { SetColumnValue(Columns.IdNhapHoc, value); }
		}
		  
		[XmlAttribute("TrangThai")]
		[Bindable(true)]
		public string TrangThai 
		{
			get { return GetColumnValue<string>(Columns.TrangThai); }
			set { SetColumnValue(Columns.TrangThai, value); }
		}
		  
		[XmlAttribute("GhiChu")]
		[Bindable(true)]
		public string GhiChu 
		{
			get { return GetColumnValue<string>(Columns.GhiChu); }
			set { SetColumnValue(Columns.GhiChu, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a LichGiangDay ActiveRecord object related to this DiemDanh
		/// 
		/// </summary>
		public Public.LichGiangDay LichGiangDay
		{
			get { return Public.LichGiangDay.FetchByID(this.IdLichGiangDay); }
			set { SetColumnValue("IdLichGiangDay", value.IdLichGiangDay); }
		}
		
		
		/// <summary>
		/// Returns a NhapHoc ActiveRecord object related to this DiemDanh
		/// 
		/// </summary>
		public Public.NhapHoc NhapHoc
		{
			get { return Public.NhapHoc.FetchByID(this.IdNhapHoc); }
			set { SetColumnValue("IdNhapHoc", value.IdNhapHoc); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,Guid varIdLichGiangDay,Guid varIdNhapHoc,string varTrangThai,string varGhiChu)
		{
			DiemDanh item = new DiemDanh();
			
			item.Id = varId;
			
			item.IdLichGiangDay = varIdLichGiangDay;
			
			item.IdNhapHoc = varIdNhapHoc;
			
			item.TrangThai = varTrangThai;
			
			item.GhiChu = varGhiChu;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,Guid varIdLichGiangDay,Guid varIdNhapHoc,string varTrangThai,string varGhiChu)
		{
			DiemDanh item = new DiemDanh();
			
				item.Id = varId;
			
				item.IdLichGiangDay = varIdLichGiangDay;
			
				item.IdNhapHoc = varIdNhapHoc;
			
				item.TrangThai = varTrangThai;
			
				item.GhiChu = varGhiChu;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdLichGiangDayColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNhapHocColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn TrangThaiColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn GhiChuColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string IdLichGiangDay = @"IdLichGiangDay";
			 public static string IdNhapHoc = @"IdNhapHoc";
			 public static string TrangThai = @"TrangThai";
			 public static string GhiChu = @"GhiChu";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
