using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    /// <summary>
    /// Controller class for DotKiemTra
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DotKiemTraController
    {
        // Preload our schema..
        DotKiemTra thisSchemaLoad = new DotKiemTra();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DotKiemTraCollection FetchAll()
        {
            DotKiemTraCollection coll = new DotKiemTraCollection();
            Query qry = new Query(DotKiemTra.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DotKiemTraCollection FetchByID(object IdDotKiemTra)
        {
            DotKiemTraCollection coll = new DotKiemTraCollection().Where("IdDotKiemTra", IdDotKiemTra).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DotKiemTraCollection FetchByQuery(Query qry)
        {
            DotKiemTraCollection coll = new DotKiemTraCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdDotKiemTra)
        {
            return (DotKiemTra.Delete(IdDotKiemTra) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdDotKiemTra)
        {
            return (DotKiemTra.Destroy(IdDotKiemTra) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public DotKiemTra Insert(DotKiemTra item)
	    {
		   
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public DotKiemTra Update(DotKiemTra item)
	    {
		  
				
	        item.Save(UserName);
            return item;
	    }
    }
}
