using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    /// <summary>
    /// Controller class for DotTuyenSinh
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DotTuyenSinhController
    {
        // Preload our schema..
        DotTuyenSinh thisSchemaLoad = new DotTuyenSinh();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DotTuyenSinhCollection FetchAll()
        {
            DotTuyenSinhCollection coll = new DotTuyenSinhCollection();
            Query qry = new Query(DotTuyenSinh.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DotTuyenSinhCollection FetchByID(object IdDotTuyenSinh)
        {
            DotTuyenSinhCollection coll = new DotTuyenSinhCollection().Where("IdDotTuyenSinh", IdDotTuyenSinh).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DotTuyenSinhCollection FetchByQuery(Query qry)
        {
            DotTuyenSinhCollection coll = new DotTuyenSinhCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdDotTuyenSinh)
        {
            return (DotTuyenSinh.Delete(IdDotTuyenSinh) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdDotTuyenSinh)
        {
            return (DotTuyenSinh.Destroy(IdDotTuyenSinh) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public DotTuyenSinh Insert(DotTuyenSinh item)
	    {
		   
	    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public DotTuyenSinh Update(DotTuyenSinh item)
	    {
		   
	        item.Save(UserName);
            return item;
	    }
    }
}
