using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
	/// <summary>
	/// Strongly-typed collection for the DotTuyenSinh class.
	/// </summary>
    [Serializable]
	public partial class DotTuyenSinhCollection : ActiveList<DotTuyenSinh, DotTuyenSinhCollection>
	{	   
		public DotTuyenSinhCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>DotTuyenSinhCollection</returns>
		public DotTuyenSinhCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                DotTuyenSinh o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the DotTuyenSinh table.
	/// </summary>
	[Serializable]
	public partial class DotTuyenSinh : ActiveRecord<DotTuyenSinh>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public DotTuyenSinh()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public DotTuyenSinh(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public DotTuyenSinh(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public DotTuyenSinh(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("DotTuyenSinh", TableType.Table, DataService.GetInstance("QLSUN"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdDotTuyenSinh = new TableSchema.TableColumn(schema);
				colvarIdDotTuyenSinh.ColumnName = "IdDotTuyenSinh";
				colvarIdDotTuyenSinh.DataType = DbType.Guid;
				colvarIdDotTuyenSinh.MaxLength = 0;
				colvarIdDotTuyenSinh.AutoIncrement = false;
				colvarIdDotTuyenSinh.IsNullable = false;
				colvarIdDotTuyenSinh.IsPrimaryKey = true;
				colvarIdDotTuyenSinh.IsForeignKey = false;
				colvarIdDotTuyenSinh.IsReadOnly = false;
				
						colvarIdDotTuyenSinh.DefaultSetting = @"(newid())";
				colvarIdDotTuyenSinh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdDotTuyenSinh);
				
				TableSchema.TableColumn colvarTenDotTuyenSinh = new TableSchema.TableColumn(schema);
				colvarTenDotTuyenSinh.ColumnName = "TenDotTuyenSinh";
				colvarTenDotTuyenSinh.DataType = DbType.String;
				colvarTenDotTuyenSinh.MaxLength = 50;
				colvarTenDotTuyenSinh.AutoIncrement = false;
				colvarTenDotTuyenSinh.IsNullable = true;
				colvarTenDotTuyenSinh.IsPrimaryKey = false;
				colvarTenDotTuyenSinh.IsForeignKey = false;
				colvarTenDotTuyenSinh.IsReadOnly = false;
				colvarTenDotTuyenSinh.DefaultSetting = @"";
				colvarTenDotTuyenSinh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenDotTuyenSinh);
				
				TableSchema.TableColumn colvarThoiGian = new TableSchema.TableColumn(schema);
				colvarThoiGian.ColumnName = "ThoiGian";
				colvarThoiGian.DataType = DbType.DateTime;
				colvarThoiGian.MaxLength = 0;
				colvarThoiGian.AutoIncrement = false;
				colvarThoiGian.IsNullable = false;
				colvarThoiGian.IsPrimaryKey = false;
				colvarThoiGian.IsForeignKey = false;
				colvarThoiGian.IsReadOnly = false;
				colvarThoiGian.DefaultSetting = @"";
				colvarThoiGian.ForeignKeyTableName = "";
				schema.Columns.Add(colvarThoiGian);
				
				TableSchema.TableColumn colvarTrangThai = new TableSchema.TableColumn(schema);
				colvarTrangThai.ColumnName = "TrangThai";
				colvarTrangThai.DataType = DbType.String;
				colvarTrangThai.MaxLength = 20;
				colvarTrangThai.AutoIncrement = false;
				colvarTrangThai.IsNullable = true;
				colvarTrangThai.IsPrimaryKey = false;
				colvarTrangThai.IsForeignKey = false;
				colvarTrangThai.IsReadOnly = false;
				colvarTrangThai.DefaultSetting = @"";
				colvarTrangThai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrangThai);
				
				TableSchema.TableColumn colvarNoiDung = new TableSchema.TableColumn(schema);
				colvarNoiDung.ColumnName = "NoiDung";
				colvarNoiDung.DataType = DbType.String;
				colvarNoiDung.MaxLength = 1073741823;
				colvarNoiDung.AutoIncrement = false;
				colvarNoiDung.IsNullable = true;
				colvarNoiDung.IsPrimaryKey = false;
				colvarNoiDung.IsForeignKey = false;
				colvarNoiDung.IsReadOnly = false;
				colvarNoiDung.DefaultSetting = @"";
				colvarNoiDung.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNoiDung);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["QLSUN"].AddSchema("DotTuyenSinh",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdDotTuyenSinh")]
		[Bindable(true)]
		public Guid IdDotTuyenSinh 
		{
			get { return GetColumnValue<Guid>(Columns.IdDotTuyenSinh); }
			set { SetColumnValue(Columns.IdDotTuyenSinh, value); }
		}
		  
		[XmlAttribute("TenDotTuyenSinh")]
		[Bindable(true)]
		public string TenDotTuyenSinh 
		{
			get { return GetColumnValue<string>(Columns.TenDotTuyenSinh); }
			set { SetColumnValue(Columns.TenDotTuyenSinh, value); }
		}
		  
		[XmlAttribute("ThoiGian")]
		[Bindable(true)]
		public DateTime ThoiGian 
		{
			get { return GetColumnValue<DateTime>(Columns.ThoiGian); }
			set { SetColumnValue(Columns.ThoiGian, value); }
		}
		  
		[XmlAttribute("TrangThai")]
		[Bindable(true)]
		public string TrangThai 
		{
			get { return GetColumnValue<string>(Columns.TrangThai); }
			set { SetColumnValue(Columns.TrangThai, value); }
		}
		  
		[XmlAttribute("NoiDung")]
		[Bindable(true)]
		public string NoiDung 
		{
			get { return GetColumnValue<string>(Columns.NoiDung); }
			set { SetColumnValue(Columns.NoiDung, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		public Public.KetQuaTuyenSinhCollection KetQuaTuyenSinhRecords()
		{
			return new Public.KetQuaTuyenSinhCollection().Where(KetQuaTuyenSinh.Columns.IdDotTuyenSinh, IdDotTuyenSinh).Load();
		}
		#endregion
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdDotTuyenSinh,string varTenDotTuyenSinh,DateTime varThoiGian,string varTrangThai,string varNoiDung)
		{
			DotTuyenSinh item = new DotTuyenSinh();
			
			item.IdDotTuyenSinh = varIdDotTuyenSinh;
			
			item.TenDotTuyenSinh = varTenDotTuyenSinh;
			
			item.ThoiGian = varThoiGian;
			
			item.TrangThai = varTrangThai;
			
			item.NoiDung = varNoiDung;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdDotTuyenSinh,string varTenDotTuyenSinh,DateTime varThoiGian,string varTrangThai,string varNoiDung)
		{
			DotTuyenSinh item = new DotTuyenSinh();
			
				item.IdDotTuyenSinh = varIdDotTuyenSinh;
			
				item.TenDotTuyenSinh = varTenDotTuyenSinh;
			
				item.ThoiGian = varThoiGian;
			
				item.TrangThai = varTrangThai;
			
				item.NoiDung = varNoiDung;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdDotTuyenSinhColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TenDotTuyenSinhColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ThoiGianColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn TrangThaiColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn NoiDungColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdDotTuyenSinh = @"IdDotTuyenSinh";
			 public static string TenDotTuyenSinh = @"TenDotTuyenSinh";
			 public static string ThoiGian = @"ThoiGian";
			 public static string TrangThai = @"TrangThai";
			 public static string NoiDung = @"NoiDung";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
}
        #endregion
	}
}
