using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    public partial class GiaoVien
    {
        
        public Int32 Tong { get; set; }
    }
    /// <summary>
    /// Controller class for GiaoVien
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class GiaoVienController
    {
        // Preload our schema..
        GiaoVien thisSchemaLoad = new GiaoVien();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public GiaoVienCollection FetchAll()
        {
            GiaoVienCollection coll = new GiaoVienCollection();
            Query qry = new Query(GiaoVien.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public GiaoVienCollection FetchByID(object IdGiaoVien)
        {
            GiaoVienCollection coll = new GiaoVienCollection().Where("IdGiaoVien", IdGiaoVien).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public GiaoVienCollection FetchByQuery(Query qry)
        {
            GiaoVienCollection coll = new GiaoVienCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdGiaoVien)
        {
            return (GiaoVien.Delete(IdGiaoVien) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdGiaoVien)
        {
            return (GiaoVien.Destroy(IdGiaoVien) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public GiaoVien Insert(GiaoVien item)
	    {
		    
	    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public GiaoVien Update(GiaoVien item)
	    {
		   
	        item.Save(UserName);
            return item;
	    }
    }
}
