using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
	/// <summary>
	/// Strongly-typed collection for the GiaoVien class.
	/// </summary>
    [Serializable]
	public partial class GiaoVienCollection : ActiveList<GiaoVien, GiaoVienCollection>
	{	   
		public GiaoVienCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>GiaoVienCollection</returns>
		public GiaoVienCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                GiaoVien o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the GiaoVien table.
	/// </summary>
	[Serializable]
	public partial class GiaoVien : ActiveRecord<GiaoVien>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public GiaoVien()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public GiaoVien(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public GiaoVien(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public GiaoVien(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("GiaoVien", TableType.Table, DataService.GetInstance("QLSUN"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdGiaoVien = new TableSchema.TableColumn(schema);
				colvarIdGiaoVien.ColumnName = "IdGiaoVien";
				colvarIdGiaoVien.DataType = DbType.Guid;
				colvarIdGiaoVien.MaxLength = 0;
				colvarIdGiaoVien.AutoIncrement = false;
				colvarIdGiaoVien.IsNullable = false;
				colvarIdGiaoVien.IsPrimaryKey = true;
				colvarIdGiaoVien.IsForeignKey = false;
				colvarIdGiaoVien.IsReadOnly = false;
				
						colvarIdGiaoVien.DefaultSetting = @"(newid())";
				colvarIdGiaoVien.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdGiaoVien);
				
				TableSchema.TableColumn colvarHoTen = new TableSchema.TableColumn(schema);
				colvarHoTen.ColumnName = "HoTen";
				colvarHoTen.DataType = DbType.String;
				colvarHoTen.MaxLength = 50;
				colvarHoTen.AutoIncrement = false;
				colvarHoTen.IsNullable = true;
				colvarHoTen.IsPrimaryKey = false;
				colvarHoTen.IsForeignKey = false;
				colvarHoTen.IsReadOnly = false;
				colvarHoTen.DefaultSetting = @"";
				colvarHoTen.ForeignKeyTableName = "";
				schema.Columns.Add(colvarHoTen);
				
				TableSchema.TableColumn colvarNamSinh = new TableSchema.TableColumn(schema);
				colvarNamSinh.ColumnName = "NamSinh";
				colvarNamSinh.DataType = DbType.DateTime;
				colvarNamSinh.MaxLength = 0;
				colvarNamSinh.AutoIncrement = false;
				colvarNamSinh.IsNullable = false;
				colvarNamSinh.IsPrimaryKey = false;
				colvarNamSinh.IsForeignKey = false;
				colvarNamSinh.IsReadOnly = false;
				colvarNamSinh.DefaultSetting = @"";
				colvarNamSinh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNamSinh);
				
				TableSchema.TableColumn colvarTrinhDo = new TableSchema.TableColumn(schema);
				colvarTrinhDo.ColumnName = "TrinhDo";
				colvarTrinhDo.DataType = DbType.String;
				colvarTrinhDo.MaxLength = 50;
				colvarTrinhDo.AutoIncrement = false;
				colvarTrinhDo.IsNullable = true;
				colvarTrinhDo.IsPrimaryKey = false;
				colvarTrinhDo.IsForeignKey = false;
				colvarTrinhDo.IsReadOnly = false;
				colvarTrinhDo.DefaultSetting = @"";
				colvarTrinhDo.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrinhDo);
				
				TableSchema.TableColumn colvarSdt = new TableSchema.TableColumn(schema);
				colvarSdt.ColumnName = "SDT";
				colvarSdt.DataType = DbType.AnsiString;
				colvarSdt.MaxLength = 15;
				colvarSdt.AutoIncrement = false;
				colvarSdt.IsNullable = true;
				colvarSdt.IsPrimaryKey = false;
				colvarSdt.IsForeignKey = false;
				colvarSdt.IsReadOnly = false;
				colvarSdt.DefaultSetting = @"";
				colvarSdt.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSdt);
				
				TableSchema.TableColumn colvarDiaChi = new TableSchema.TableColumn(schema);
				colvarDiaChi.ColumnName = "DiaChi";
				colvarDiaChi.DataType = DbType.String;
				colvarDiaChi.MaxLength = 100;
				colvarDiaChi.AutoIncrement = false;
				colvarDiaChi.IsNullable = true;
				colvarDiaChi.IsPrimaryKey = false;
				colvarDiaChi.IsForeignKey = false;
				colvarDiaChi.IsReadOnly = false;
				colvarDiaChi.DefaultSetting = @"";
				colvarDiaChi.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDiaChi);
				
				TableSchema.TableColumn colvarEmail = new TableSchema.TableColumn(schema);
				colvarEmail.ColumnName = "Email";
				colvarEmail.DataType = DbType.AnsiString;
				colvarEmail.MaxLength = 50;
				colvarEmail.AutoIncrement = false;
				colvarEmail.IsNullable = true;
				colvarEmail.IsPrimaryKey = false;
				colvarEmail.IsForeignKey = false;
				colvarEmail.IsReadOnly = false;
				colvarEmail.DefaultSetting = @"";
				colvarEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarEmail);
				
				TableSchema.TableColumn colvarNgayVaoLam = new TableSchema.TableColumn(schema);
				colvarNgayVaoLam.ColumnName = "NgayVaoLam";
				colvarNgayVaoLam.DataType = DbType.DateTime;
				colvarNgayVaoLam.MaxLength = 0;
				colvarNgayVaoLam.AutoIncrement = false;
				colvarNgayVaoLam.IsNullable = false;
				colvarNgayVaoLam.IsPrimaryKey = false;
				colvarNgayVaoLam.IsForeignKey = false;
				colvarNgayVaoLam.IsReadOnly = false;
				colvarNgayVaoLam.DefaultSetting = @"";
				colvarNgayVaoLam.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayVaoLam);
				
				TableSchema.TableColumn colvarTrangThai = new TableSchema.TableColumn(schema);
				colvarTrangThai.ColumnName = "TrangThai";
				colvarTrangThai.DataType = DbType.String;
				colvarTrangThai.MaxLength = 20;
				colvarTrangThai.AutoIncrement = false;
				colvarTrangThai.IsNullable = true;
				colvarTrangThai.IsPrimaryKey = false;
				colvarTrangThai.IsForeignKey = false;
				colvarTrangThai.IsReadOnly = false;
				colvarTrangThai.DefaultSetting = @"";
				colvarTrangThai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrangThai);
				
				TableSchema.TableColumn colvarGioiTinh = new TableSchema.TableColumn(schema);
				colvarGioiTinh.ColumnName = "GioiTinh";
				colvarGioiTinh.DataType = DbType.String;
				colvarGioiTinh.MaxLength = 5;
				colvarGioiTinh.AutoIncrement = false;
				colvarGioiTinh.IsNullable = true;
				colvarGioiTinh.IsPrimaryKey = false;
				colvarGioiTinh.IsForeignKey = false;
				colvarGioiTinh.IsReadOnly = false;
				colvarGioiTinh.DefaultSetting = @"";
				colvarGioiTinh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGioiTinh);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["QLSUN"].AddSchema("GiaoVien",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdGiaoVien")]
		[Bindable(true)]
		public Guid IdGiaoVien 
		{
			get { return GetColumnValue<Guid>(Columns.IdGiaoVien); }
			set { SetColumnValue(Columns.IdGiaoVien, value); }
		}
		  
		[XmlAttribute("HoTen")]
		[Bindable(true)]
		public string HoTen 
		{
			get { return GetColumnValue<string>(Columns.HoTen); }
			set { SetColumnValue(Columns.HoTen, value); }
		}
		  
		[XmlAttribute("NamSinh")]
		[Bindable(true)]
		public DateTime NamSinh 
		{
			get { return GetColumnValue<DateTime>(Columns.NamSinh); }
			set { SetColumnValue(Columns.NamSinh, value); }
		}
		  
		[XmlAttribute("TrinhDo")]
		[Bindable(true)]
		public string TrinhDo 
		{
			get { return GetColumnValue<string>(Columns.TrinhDo); }
			set { SetColumnValue(Columns.TrinhDo, value); }
		}
		  
		[XmlAttribute("Sdt")]
		[Bindable(true)]
		public string Sdt 
		{
			get { return GetColumnValue<string>(Columns.Sdt); }
			set { SetColumnValue(Columns.Sdt, value); }
		}
		  
		[XmlAttribute("DiaChi")]
		[Bindable(true)]
		public string DiaChi 
		{
			get { return GetColumnValue<string>(Columns.DiaChi); }
			set { SetColumnValue(Columns.DiaChi, value); }
		}
		  
		[XmlAttribute("Email")]
		[Bindable(true)]
		public string Email 
		{
			get { return GetColumnValue<string>(Columns.Email); }
			set { SetColumnValue(Columns.Email, value); }
		}
		  
		[XmlAttribute("NgayVaoLam")]
		[Bindable(true)]
		public DateTime NgayVaoLam 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayVaoLam); }
			set { SetColumnValue(Columns.NgayVaoLam, value); }
		}
		  
		[XmlAttribute("TrangThai")]
		[Bindable(true)]
		public string TrangThai 
		{
			get { return GetColumnValue<string>(Columns.TrangThai); }
			set { SetColumnValue(Columns.TrangThai, value); }
		}
		  
		[XmlAttribute("GioiTinh")]
		[Bindable(true)]
		public string GioiTinh 
		{
			get { return GetColumnValue<string>(Columns.GioiTinh); }
			set { SetColumnValue(Columns.GioiTinh, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		public Public.LichGiangDayCollection LichGiangDayRecords()
		{
			return new Public.LichGiangDayCollection().Where(LichGiangDay.Columns.IdGiaoVien, IdGiaoVien).Load();
		}
		public Public.NguoiDungGiaoVienCollection NguoiDungGiaoVienRecords()
		{
			return new Public.NguoiDungGiaoVienCollection().Where(NguoiDungGiaoVien.Columns.IdGiaoVien, IdGiaoVien).Load();
		}
		public Public.ThongBaoGiaoVienCollection ThongBaoGiaoVienRecords()
		{
			return new Public.ThongBaoGiaoVienCollection().Where(ThongBaoGiaoVien.Columns.IdGiaoVien, IdGiaoVien).Load();
		}
		#endregion
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdGiaoVien,string varHoTen,DateTime varNamSinh,string varTrinhDo,string varSdt,string varDiaChi,string varEmail,DateTime varNgayVaoLam,string varTrangThai,string varGioiTinh)
		{
			GiaoVien item = new GiaoVien();
			
			item.IdGiaoVien = varIdGiaoVien;
			
			item.HoTen = varHoTen;
			
			item.NamSinh = varNamSinh;
			
			item.TrinhDo = varTrinhDo;
			
			item.Sdt = varSdt;
			
			item.DiaChi = varDiaChi;
			
			item.Email = varEmail;
			
			item.NgayVaoLam = varNgayVaoLam;
			
			item.TrangThai = varTrangThai;
			
			item.GioiTinh = varGioiTinh;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdGiaoVien,string varHoTen,DateTime varNamSinh,string varTrinhDo,string varSdt,string varDiaChi,string varEmail,DateTime varNgayVaoLam,string varTrangThai,string varGioiTinh)
		{
			GiaoVien item = new GiaoVien();
			
				item.IdGiaoVien = varIdGiaoVien;
			
				item.HoTen = varHoTen;
			
				item.NamSinh = varNamSinh;
			
				item.TrinhDo = varTrinhDo;
			
				item.Sdt = varSdt;
			
				item.DiaChi = varDiaChi;
			
				item.Email = varEmail;
			
				item.NgayVaoLam = varNgayVaoLam;
			
				item.TrangThai = varTrangThai;
			
				item.GioiTinh = varGioiTinh;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdGiaoVienColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn HoTenColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn NamSinhColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn TrinhDoColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn SdtColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn DiaChiColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn EmailColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayVaoLamColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn TrangThaiColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn GioiTinhColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdGiaoVien = @"IdGiaoVien";
			 public static string HoTen = @"HoTen";
			 public static string NamSinh = @"NamSinh";
			 public static string TrinhDo = @"TrinhDo";
			 public static string Sdt = @"SDT";
			 public static string DiaChi = @"DiaChi";
			 public static string Email = @"Email";
			 public static string NgayVaoLam = @"NgayVaoLam";
			 public static string TrangThai = @"TrangThai";
			 public static string GioiTinh = @"GioiTinh";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
}
        #endregion
	}
}
