using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
	/// <summary>
	/// Strongly-typed collection for the HocPhi class.
	/// </summary>
    [Serializable]
	public partial class HocPhiCollection : ActiveList<HocPhi, HocPhiCollection>
	{	   
		public HocPhiCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>HocPhiCollection</returns>
		public HocPhiCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                HocPhi o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the HocPhi table.
	/// </summary>
	[Serializable]
	public partial class HocPhi : ActiveRecord<HocPhi>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public HocPhi()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public HocPhi(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public HocPhi(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public HocPhi(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("HocPhi", TableType.Table, DataService.GetInstance("QLSUN"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				
						colvarId.DefaultSetting = @"(newid())";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarIdNhapHoc = new TableSchema.TableColumn(schema);
				colvarIdNhapHoc.ColumnName = "IdNhapHoc";
				colvarIdNhapHoc.DataType = DbType.Guid;
				colvarIdNhapHoc.MaxLength = 0;
				colvarIdNhapHoc.AutoIncrement = false;
				colvarIdNhapHoc.IsNullable = false;
				colvarIdNhapHoc.IsPrimaryKey = false;
				colvarIdNhapHoc.IsForeignKey = true;
				colvarIdNhapHoc.IsReadOnly = false;
				colvarIdNhapHoc.DefaultSetting = @"";
				
					colvarIdNhapHoc.ForeignKeyTableName = "NhapHoc";
				schema.Columns.Add(colvarIdNhapHoc);
				
				TableSchema.TableColumn colvarTienThanhToan = new TableSchema.TableColumn(schema);
				colvarTienThanhToan.ColumnName = "TienThanhToan";
				colvarTienThanhToan.DataType = DbType.Decimal;
				colvarTienThanhToan.MaxLength = 0;
				colvarTienThanhToan.AutoIncrement = false;
				colvarTienThanhToan.IsNullable = true;
				colvarTienThanhToan.IsPrimaryKey = false;
				colvarTienThanhToan.IsForeignKey = false;
				colvarTienThanhToan.IsReadOnly = false;
				colvarTienThanhToan.DefaultSetting = @"";
				colvarTienThanhToan.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTienThanhToan);
				
				TableSchema.TableColumn colvarGiamTru = new TableSchema.TableColumn(schema);
				colvarGiamTru.ColumnName = "GiamTru";
				colvarGiamTru.DataType = DbType.Decimal;
				colvarGiamTru.MaxLength = 0;
				colvarGiamTru.AutoIncrement = false;
				colvarGiamTru.IsNullable = true;
				colvarGiamTru.IsPrimaryKey = false;
				colvarGiamTru.IsForeignKey = false;
				colvarGiamTru.IsReadOnly = false;
				colvarGiamTru.DefaultSetting = @"";
				colvarGiamTru.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGiamTru);
				
				TableSchema.TableColumn colvarThoiGianDong = new TableSchema.TableColumn(schema);
				colvarThoiGianDong.ColumnName = "ThoiGianDong";
				colvarThoiGianDong.DataType = DbType.DateTime;
				colvarThoiGianDong.MaxLength = 0;
				colvarThoiGianDong.AutoIncrement = false;
				colvarThoiGianDong.IsNullable = false;
				colvarThoiGianDong.IsPrimaryKey = false;
				colvarThoiGianDong.IsForeignKey = false;
				colvarThoiGianDong.IsReadOnly = false;
				colvarThoiGianDong.DefaultSetting = @"";
				colvarThoiGianDong.ForeignKeyTableName = "";
				schema.Columns.Add(colvarThoiGianDong);
				
				TableSchema.TableColumn colvarHanDong = new TableSchema.TableColumn(schema);
				colvarHanDong.ColumnName = "HanDong";
				colvarHanDong.DataType = DbType.DateTime;
				colvarHanDong.MaxLength = 0;
				colvarHanDong.AutoIncrement = false;
				colvarHanDong.IsNullable = false;
				colvarHanDong.IsPrimaryKey = false;
				colvarHanDong.IsForeignKey = false;
				colvarHanDong.IsReadOnly = false;
				colvarHanDong.DefaultSetting = @"";
				colvarHanDong.ForeignKeyTableName = "";
				schema.Columns.Add(colvarHanDong);
				
				TableSchema.TableColumn colvarGhiChu = new TableSchema.TableColumn(schema);
				colvarGhiChu.ColumnName = "GhiChu";
				colvarGhiChu.DataType = DbType.String;
				colvarGhiChu.MaxLength = 1073741823;
				colvarGhiChu.AutoIncrement = false;
				colvarGhiChu.IsNullable = true;
				colvarGhiChu.IsPrimaryKey = false;
				colvarGhiChu.IsForeignKey = false;
				colvarGhiChu.IsReadOnly = false;
				colvarGhiChu.DefaultSetting = @"";
				colvarGhiChu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGhiChu);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["QLSUN"].AddSchema("HocPhi",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("IdNhapHoc")]
		[Bindable(true)]
		public Guid IdNhapHoc 
		{
			get { return GetColumnValue<Guid>(Columns.IdNhapHoc); }
			set { SetColumnValue(Columns.IdNhapHoc, value); }
		}
		  
		[XmlAttribute("TienThanhToan")]
		[Bindable(true)]
		public decimal? TienThanhToan 
		{
			get { return GetColumnValue<decimal?>(Columns.TienThanhToan); }
			set { SetColumnValue(Columns.TienThanhToan, value); }
		}
		  
		[XmlAttribute("GiamTru")]
		[Bindable(true)]
		public decimal? GiamTru 
		{
			get { return GetColumnValue<decimal?>(Columns.GiamTru); }
			set { SetColumnValue(Columns.GiamTru, value); }
		}
		  
		[XmlAttribute("ThoiGianDong")]
		[Bindable(true)]
		public DateTime ThoiGianDong 
		{
			get { return GetColumnValue<DateTime>(Columns.ThoiGianDong); }
			set { SetColumnValue(Columns.ThoiGianDong, value); }
		}
		  
		[XmlAttribute("HanDong")]
		[Bindable(true)]
		public DateTime HanDong 
		{
			get { return GetColumnValue<DateTime>(Columns.HanDong); }
			set { SetColumnValue(Columns.HanDong, value); }
		}
		  
		[XmlAttribute("GhiChu")]
		[Bindable(true)]
		public string GhiChu 
		{
			get { return GetColumnValue<string>(Columns.GhiChu); }
			set { SetColumnValue(Columns.GhiChu, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a NhapHoc ActiveRecord object related to this HocPhi
		/// 
		/// </summary>
		public Public.NhapHoc NhapHoc
		{
			get { return Public.NhapHoc.FetchByID(this.IdNhapHoc); }
			set { SetColumnValue("IdNhapHoc", value.IdNhapHoc); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,Guid varIdNhapHoc,decimal? varTienThanhToan,decimal? varGiamTru,DateTime varThoiGianDong,DateTime varHanDong,string varGhiChu)
		{
			HocPhi item = new HocPhi();
			
			item.Id = varId;
			
			item.IdNhapHoc = varIdNhapHoc;
			
			item.TienThanhToan = varTienThanhToan;
			
			item.GiamTru = varGiamTru;
			
			item.ThoiGianDong = varThoiGianDong;
			
			item.HanDong = varHanDong;
			
			item.GhiChu = varGhiChu;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,Guid varIdNhapHoc,decimal? varTienThanhToan,decimal? varGiamTru,DateTime varThoiGianDong,DateTime varHanDong,string varGhiChu)
		{
			HocPhi item = new HocPhi();
			
				item.Id = varId;
			
				item.IdNhapHoc = varIdNhapHoc;
			
				item.TienThanhToan = varTienThanhToan;
			
				item.GiamTru = varGiamTru;
			
				item.ThoiGianDong = varThoiGianDong;
			
				item.HanDong = varHanDong;
			
				item.GhiChu = varGhiChu;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNhapHocColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn TienThanhToanColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn GiamTruColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn ThoiGianDongColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn HanDongColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn GhiChuColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string IdNhapHoc = @"IdNhapHoc";
			 public static string TienThanhToan = @"TienThanhToan";
			 public static string GiamTru = @"GiamTru";
			 public static string ThoiGianDong = @"ThoiGianDong";
			 public static string HanDong = @"HanDong";
			 public static string GhiChu = @"GhiChu";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
