using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
	/// <summary>
	/// Strongly-typed collection for the KetQuaHocTap class.
	/// </summary>
    [Serializable]
	public partial class KetQuaHocTapCollection : ActiveList<KetQuaHocTap, KetQuaHocTapCollection>
	{	   
		public KetQuaHocTapCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>KetQuaHocTapCollection</returns>
		public KetQuaHocTapCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                KetQuaHocTap o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the KetQuaHocTap table.
	/// </summary>
	[Serializable]
	public partial class KetQuaHocTap : ActiveRecord<KetQuaHocTap>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public KetQuaHocTap()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public KetQuaHocTap(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public KetQuaHocTap(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public KetQuaHocTap(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("KetQuaHocTap", TableType.Table, DataService.GetInstance("QLSUN"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				
						colvarId.DefaultSetting = @"(newid())";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarIdDotKiemTra = new TableSchema.TableColumn(schema);
				colvarIdDotKiemTra.ColumnName = "IdDotKiemTra";
				colvarIdDotKiemTra.DataType = DbType.Guid;
				colvarIdDotKiemTra.MaxLength = 0;
				colvarIdDotKiemTra.AutoIncrement = false;
				colvarIdDotKiemTra.IsNullable = false;
				colvarIdDotKiemTra.IsPrimaryKey = false;
				colvarIdDotKiemTra.IsForeignKey = true;
				colvarIdDotKiemTra.IsReadOnly = false;
				colvarIdDotKiemTra.DefaultSetting = @"";
				
					colvarIdDotKiemTra.ForeignKeyTableName = "DotKiemTra";
				schema.Columns.Add(colvarIdDotKiemTra);
				
				TableSchema.TableColumn colvarIdNhapHoc = new TableSchema.TableColumn(schema);
				colvarIdNhapHoc.ColumnName = "IdNhapHoc";
				colvarIdNhapHoc.DataType = DbType.Guid;
				colvarIdNhapHoc.MaxLength = 0;
				colvarIdNhapHoc.AutoIncrement = false;
				colvarIdNhapHoc.IsNullable = false;
				colvarIdNhapHoc.IsPrimaryKey = false;
				colvarIdNhapHoc.IsForeignKey = true;
				colvarIdNhapHoc.IsReadOnly = false;
				colvarIdNhapHoc.DefaultSetting = @"";
				
					colvarIdNhapHoc.ForeignKeyTableName = "NhapHoc";
				schema.Columns.Add(colvarIdNhapHoc);
				
				TableSchema.TableColumn colvarDiem = new TableSchema.TableColumn(schema);
				colvarDiem.ColumnName = "Diem";
				colvarDiem.DataType = DbType.String;
				colvarDiem.MaxLength = 5;
				colvarDiem.AutoIncrement = false;
				colvarDiem.IsNullable = true;
				colvarDiem.IsPrimaryKey = false;
				colvarDiem.IsForeignKey = false;
				colvarDiem.IsReadOnly = false;
				colvarDiem.DefaultSetting = @"";
				colvarDiem.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDiem);
				
				TableSchema.TableColumn colvarGhiChu = new TableSchema.TableColumn(schema);
				colvarGhiChu.ColumnName = "GhiChu";
				colvarGhiChu.DataType = DbType.String;
				colvarGhiChu.MaxLength = 1073741823;
				colvarGhiChu.AutoIncrement = false;
				colvarGhiChu.IsNullable = true;
				colvarGhiChu.IsPrimaryKey = false;
				colvarGhiChu.IsForeignKey = false;
				colvarGhiChu.IsReadOnly = false;
				colvarGhiChu.DefaultSetting = @"";
				colvarGhiChu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGhiChu);
				
				TableSchema.TableColumn colvarThoiGian = new TableSchema.TableColumn(schema);
				colvarThoiGian.ColumnName = "ThoiGian";
				colvarThoiGian.DataType = DbType.DateTime;
				colvarThoiGian.MaxLength = 0;
				colvarThoiGian.AutoIncrement = false;
				colvarThoiGian.IsNullable = false;
				colvarThoiGian.IsPrimaryKey = false;
				colvarThoiGian.IsForeignKey = false;
				colvarThoiGian.IsReadOnly = false;
				colvarThoiGian.DefaultSetting = @"";
				colvarThoiGian.ForeignKeyTableName = "";
				schema.Columns.Add(colvarThoiGian);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["QLSUN"].AddSchema("KetQuaHocTap",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("IdDotKiemTra")]
		[Bindable(true)]
		public Guid IdDotKiemTra 
		{
			get { return GetColumnValue<Guid>(Columns.IdDotKiemTra); }
			set { SetColumnValue(Columns.IdDotKiemTra, value); }
		}
		  
		[XmlAttribute("IdNhapHoc")]
		[Bindable(true)]
		public Guid IdNhapHoc 
		{
			get { return GetColumnValue<Guid>(Columns.IdNhapHoc); }
			set { SetColumnValue(Columns.IdNhapHoc, value); }
		}
		  
		[XmlAttribute("Diem")]
		[Bindable(true)]
		public string Diem 
		{
			get { return GetColumnValue<string>(Columns.Diem); }
			set { SetColumnValue(Columns.Diem, value); }
		}
		  
		[XmlAttribute("GhiChu")]
		[Bindable(true)]
		public string GhiChu 
		{
			get { return GetColumnValue<string>(Columns.GhiChu); }
			set { SetColumnValue(Columns.GhiChu, value); }
		}
		  
		[XmlAttribute("ThoiGian")]
		[Bindable(true)]
		public DateTime ThoiGian 
		{
			get { return GetColumnValue<DateTime>(Columns.ThoiGian); }
			set { SetColumnValue(Columns.ThoiGian, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a DotKiemTra ActiveRecord object related to this KetQuaHocTap
		/// 
		/// </summary>
		public Public.DotKiemTra DotKiemTra
		{
			get { return Public.DotKiemTra.FetchByID(this.IdDotKiemTra); }
			set { SetColumnValue("IdDotKiemTra", value.IdDotKiemTra); }
		}
		
		
		/// <summary>
		/// Returns a NhapHoc ActiveRecord object related to this KetQuaHocTap
		/// 
		/// </summary>
		public Public.NhapHoc NhapHoc
		{
			get { return Public.NhapHoc.FetchByID(this.IdNhapHoc); }
			set { SetColumnValue("IdNhapHoc", value.IdNhapHoc); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,Guid varIdDotKiemTra,Guid varIdNhapHoc,string varDiem,string varGhiChu,DateTime varThoiGian)
		{
			KetQuaHocTap item = new KetQuaHocTap();
			
			item.Id = varId;
			
			item.IdDotKiemTra = varIdDotKiemTra;
			
			item.IdNhapHoc = varIdNhapHoc;
			
			item.Diem = varDiem;
			
			item.GhiChu = varGhiChu;
			
			item.ThoiGian = varThoiGian;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,Guid varIdDotKiemTra,Guid varIdNhapHoc,string varDiem,string varGhiChu,DateTime varThoiGian)
		{
			KetQuaHocTap item = new KetQuaHocTap();
			
				item.Id = varId;
			
				item.IdDotKiemTra = varIdDotKiemTra;
			
				item.IdNhapHoc = varIdNhapHoc;
			
				item.Diem = varDiem;
			
				item.GhiChu = varGhiChu;
			
				item.ThoiGian = varThoiGian;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdDotKiemTraColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNhapHocColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn DiemColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn GhiChuColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn ThoiGianColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string IdDotKiemTra = @"IdDotKiemTra";
			 public static string IdNhapHoc = @"IdNhapHoc";
			 public static string Diem = @"Diem";
			 public static string GhiChu = @"GhiChu";
			 public static string ThoiGian = @"ThoiGian";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
