using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    public partial class KetQuaHocTap
    {
        public string HoTen { get; set; }
        public string TenLop { get; set; }
        public string Ten { get; set; }
    }


    /// <summary>
    /// Controller class for KetQuaHocTap
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class KetQuaHocTapController
    {
        // Preload our schema..
        KetQuaHocTap thisSchemaLoad = new KetQuaHocTap();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public KetQuaHocTapCollection FetchAll()
        {
            KetQuaHocTapCollection coll = new KetQuaHocTapCollection();
            Query qry = new Query(KetQuaHocTap.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public KetQuaHocTapCollection FetchByID(object Id)
        {
            KetQuaHocTapCollection coll = new KetQuaHocTapCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public KetQuaHocTapCollection FetchByQuery(Query qry)
        {
            KetQuaHocTapCollection coll = new KetQuaHocTapCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (KetQuaHocTap.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (KetQuaHocTap.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public KetQuaHocTap Insert(KetQuaHocTap item)
	    {
		   
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public KetQuaHocTap Update(KetQuaHocTap item)
	    {
		   
	        item.Save(UserName);
            return item;
	    }
    }
}
