using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    public partial class KetQuaTuyenSinh
    {
        public string HoTen { get; set; }
        public string TenDotTuyenSinh { get; set; }
        public DateTime ThoiGian { get; set; }
    }

    /// <summary>
    /// Controller class for KetQuaTuyenSinh
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class KetQuaTuyenSinhController
    {
        // Preload our schema..
        KetQuaTuyenSinh thisSchemaLoad = new KetQuaTuyenSinh();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public KetQuaTuyenSinhCollection FetchAll()
        {
            KetQuaTuyenSinhCollection coll = new KetQuaTuyenSinhCollection();
            Query qry = new Query(KetQuaTuyenSinh.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public KetQuaTuyenSinhCollection FetchByID(object Id)
        {
            KetQuaTuyenSinhCollection coll = new KetQuaTuyenSinhCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public KetQuaTuyenSinhCollection FetchByQuery(Query qry)
        {
            KetQuaTuyenSinhCollection coll = new KetQuaTuyenSinhCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (KetQuaTuyenSinh.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (KetQuaTuyenSinh.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public KetQuaTuyenSinh Insert(KetQuaTuyenSinh item)
	    {
		   
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public KetQuaTuyenSinh Update(KetQuaTuyenSinh item)
	    {
		   
				
	        item.Save(UserName);
            return item;
	    }
    }
}
