using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    /// <summary>
    /// Controller class for KhoaHoc
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class KhoaHocController
    {
        // Preload our schema..
        KhoaHoc thisSchemaLoad = new KhoaHoc();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public KhoaHocCollection FetchAll()
        {
            KhoaHocCollection coll = new KhoaHocCollection();
            Query qry = new Query(KhoaHoc.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public KhoaHocCollection FetchByID(object IdKhoaHoc)
        {
            KhoaHocCollection coll = new KhoaHocCollection().Where("IdKhoaHoc", IdKhoaHoc).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public KhoaHocCollection FetchByQuery(Query qry)
        {
            KhoaHocCollection coll = new KhoaHocCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdKhoaHoc)
        {
            return (KhoaHoc.Delete(IdKhoaHoc) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdKhoaHoc)
        {
            return (KhoaHoc.Destroy(IdKhoaHoc) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public KhoaHoc Insert(KhoaHoc item)
	    {
		    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public KhoaHoc Update(KhoaHoc item)
	    {
		   
	        item.Save(UserName);
            return item;
	    }
    }
}
