using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    public partial class Lop
    {
        public string TenKhoaHoc { get; set; }
        public Int32 Tong { get; set; }
    }

    /// <summary>
    /// Controller class for Lop
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class LopController
    {
        // Preload our schema..
        Lop thisSchemaLoad = new Lop();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public LopCollection FetchAll()
        {
            LopCollection coll = new LopCollection();
            Query qry = new Query(Lop.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public LopCollection FetchByID(object IdLop)
        {
            LopCollection coll = new LopCollection().Where("IdLop", IdLop).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public LopCollection FetchByQuery(Query qry)
        {
            LopCollection coll = new LopCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdLop)
        {
            return (Lop.Delete(IdLop) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdLop)
        {
            return (Lop.Destroy(IdLop) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public Lop Insert(Lop item)
	    {
		    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public Lop Update(Lop item)
	    {
		    
	        item.Save(UserName);
            return item;
	    }
    }
}
