using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    public partial class NguoiDungADM
    {
        public string HoTen { get; set; }
    }

    /// <summary>
    /// Controller class for NguoiDungADM
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class NguoiDungADMController
    {
        // Preload our schema..
        NguoiDungADM thisSchemaLoad = new NguoiDungADM();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public NguoiDungADMCollection FetchAll()
        {
            NguoiDungADMCollection coll = new NguoiDungADMCollection();
            Query qry = new Query(NguoiDungADM.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public NguoiDungADMCollection FetchByID(object Id)
        {
            NguoiDungADMCollection coll = new NguoiDungADMCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public NguoiDungADMCollection FetchByQuery(Query qry)
        {
            NguoiDungADMCollection coll = new NguoiDungADMCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (NguoiDungADM.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (NguoiDungADM.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public NguoiDungADM Insert(NguoiDungADM item)
	    {
		    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public NguoiDungADM Update(NguoiDungADM item)
	    {
		   
	        item.Save(UserName);
            return item;
	    }
    }
}
