using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
	/// <summary>
	/// Strongly-typed collection for the NguoiDungADM class.
	/// </summary>
    [Serializable]
	public partial class NguoiDungADMCollection : ActiveList<NguoiDungADM, NguoiDungADMCollection>
	{	   
		public NguoiDungADMCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>NguoiDungADMCollection</returns>
		public NguoiDungADMCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                NguoiDungADM o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the NguoiDungADM table.
	/// </summary>
	[Serializable]
	public partial class NguoiDungADM : ActiveRecord<NguoiDungADM>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public NguoiDungADM()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public NguoiDungADM(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public NguoiDungADM(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public NguoiDungADM(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("NguoiDungADM", TableType.Table, DataService.GetInstance("QLSUN"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				
						colvarId.DefaultSetting = @"(newid())";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarTenTaiKhoan = new TableSchema.TableColumn(schema);
				colvarTenTaiKhoan.ColumnName = "TenTaiKhoan";
				colvarTenTaiKhoan.DataType = DbType.String;
				colvarTenTaiKhoan.MaxLength = 50;
				colvarTenTaiKhoan.AutoIncrement = false;
				colvarTenTaiKhoan.IsNullable = true;
				colvarTenTaiKhoan.IsPrimaryKey = false;
				colvarTenTaiKhoan.IsForeignKey = false;
				colvarTenTaiKhoan.IsReadOnly = false;
				colvarTenTaiKhoan.DefaultSetting = @"";
				colvarTenTaiKhoan.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenTaiKhoan);
				
				TableSchema.TableColumn colvarMatKhau = new TableSchema.TableColumn(schema);
				colvarMatKhau.ColumnName = "MatKhau";
				colvarMatKhau.DataType = DbType.String;
				colvarMatKhau.MaxLength = 30;
				colvarMatKhau.AutoIncrement = false;
				colvarMatKhau.IsNullable = true;
				colvarMatKhau.IsPrimaryKey = false;
				colvarMatKhau.IsForeignKey = false;
				colvarMatKhau.IsReadOnly = false;
				colvarMatKhau.DefaultSetting = @"";
				colvarMatKhau.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMatKhau);
				
				TableSchema.TableColumn colvarTrangThai = new TableSchema.TableColumn(schema);
				colvarTrangThai.ColumnName = "TrangThai";
				colvarTrangThai.DataType = DbType.Boolean;
				colvarTrangThai.MaxLength = 0;
				colvarTrangThai.AutoIncrement = false;
				colvarTrangThai.IsNullable = true;
				colvarTrangThai.IsPrimaryKey = false;
				colvarTrangThai.IsForeignKey = false;
				colvarTrangThai.IsReadOnly = false;
				colvarTrangThai.DefaultSetting = @"";
				colvarTrangThai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrangThai);
				
				TableSchema.TableColumn colvarIdNhanVien = new TableSchema.TableColumn(schema);
				colvarIdNhanVien.ColumnName = "IdNhanVien";
				colvarIdNhanVien.DataType = DbType.Guid;
				colvarIdNhanVien.MaxLength = 0;
				colvarIdNhanVien.AutoIncrement = false;
				colvarIdNhanVien.IsNullable = false;
				colvarIdNhanVien.IsPrimaryKey = false;
				colvarIdNhanVien.IsForeignKey = true;
				colvarIdNhanVien.IsReadOnly = false;
				colvarIdNhanVien.DefaultSetting = @"";
				
					colvarIdNhanVien.ForeignKeyTableName = "NhanVien";
				schema.Columns.Add(colvarIdNhanVien);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["QLSUN"].AddSchema("NguoiDungADM",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("TenTaiKhoan")]
		[Bindable(true)]
		public string TenTaiKhoan 
		{
			get { return GetColumnValue<string>(Columns.TenTaiKhoan); }
			set { SetColumnValue(Columns.TenTaiKhoan, value); }
		}
		  
		[XmlAttribute("MatKhau")]
		[Bindable(true)]
		public string MatKhau 
		{
			get { return GetColumnValue<string>(Columns.MatKhau); }
			set { SetColumnValue(Columns.MatKhau, value); }
		}
		  
		[XmlAttribute("TrangThai")]
		[Bindable(true)]
		public bool? TrangThai 
		{
			get { return GetColumnValue<bool?>(Columns.TrangThai); }
			set { SetColumnValue(Columns.TrangThai, value); }
		}
		  
		[XmlAttribute("IdNhanVien")]
		[Bindable(true)]
		public Guid IdNhanVien 
		{
			get { return GetColumnValue<Guid>(Columns.IdNhanVien); }
			set { SetColumnValue(Columns.IdNhanVien, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a NhanVien ActiveRecord object related to this NguoiDungADM
		/// 
		/// </summary>
		public Public.NhanVien NhanVien
		{
			get { return Public.NhanVien.FetchByID(this.IdNhanVien); }
			set { SetColumnValue("IdNhanVien", value.Id); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,string varTenTaiKhoan,string varMatKhau,bool? varTrangThai,Guid varIdNhanVien)
		{
			NguoiDungADM item = new NguoiDungADM();
			
			item.Id = varId;
			
			item.TenTaiKhoan = varTenTaiKhoan;
			
			item.MatKhau = varMatKhau;
			
			item.TrangThai = varTrangThai;
			
			item.IdNhanVien = varIdNhanVien;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,string varTenTaiKhoan,string varMatKhau,bool? varTrangThai,Guid varIdNhanVien)
		{
			NguoiDungADM item = new NguoiDungADM();
			
				item.Id = varId;
			
				item.TenTaiKhoan = varTenTaiKhoan;
			
				item.MatKhau = varMatKhau;
			
				item.TrangThai = varTrangThai;
			
				item.IdNhanVien = varIdNhanVien;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TenTaiKhoanColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn MatKhauColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn TrangThaiColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNhanVienColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string TenTaiKhoan = @"TenTaiKhoan";
			 public static string MatKhau = @"MatKhau";
			 public static string TrangThai = @"TrangThai";
			 public static string IdNhanVien = @"IdNhanVien";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
