using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    public partial class NhanVien
    {
        public string TenChucVu { get; set; }
        public decimal LuongThang { get; set; }
        public Int32 Tong { get; set; }
    }

    /// <summary>
    /// Controller class for NhanVien
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class NhanVienController
    {
        // Preload our schema..
        NhanVien thisSchemaLoad = new NhanVien();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public NhanVienCollection FetchAll()
        {
            NhanVienCollection coll = new NhanVienCollection();
            Query qry = new Query(NhanVien.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public NhanVienCollection FetchByID(object Id)
        {
            NhanVienCollection coll = new NhanVienCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public NhanVienCollection FetchByQuery(Query qry)
        {
            NhanVienCollection coll = new NhanVienCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (NhanVien.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (NhanVien.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public NhanVien Insert(NhanVien item)
	    {
		    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public NhanVien Update(NhanVien item)
	    {
		   
	        item.Save(UserName);
            return item;
	    }
    }
}
