using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
	/// <summary>
	/// Strongly-typed collection for the NhapHoc class.
	/// </summary>
    [Serializable]
	public partial class NhapHocCollection : ActiveList<NhapHoc, NhapHocCollection>
	{	   
		public NhapHocCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>NhapHocCollection</returns>
		public NhapHocCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                NhapHoc o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the NhapHoc table.
	/// </summary>
	[Serializable]
	public partial class NhapHoc : ActiveRecord<NhapHoc>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public NhapHoc()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public NhapHoc(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public NhapHoc(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public NhapHoc(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("NhapHoc", TableType.Table, DataService.GetInstance("QLSUN"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdNhapHoc = new TableSchema.TableColumn(schema);
				colvarIdNhapHoc.ColumnName = "IdNhapHoc";
				colvarIdNhapHoc.DataType = DbType.Guid;
				colvarIdNhapHoc.MaxLength = 0;
				colvarIdNhapHoc.AutoIncrement = false;
				colvarIdNhapHoc.IsNullable = false;
				colvarIdNhapHoc.IsPrimaryKey = true;
				colvarIdNhapHoc.IsForeignKey = false;
				colvarIdNhapHoc.IsReadOnly = false;
				
						colvarIdNhapHoc.DefaultSetting = @"(newid())";
				colvarIdNhapHoc.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdNhapHoc);
				
				TableSchema.TableColumn colvarIdHocVien = new TableSchema.TableColumn(schema);
				colvarIdHocVien.ColumnName = "IdHocVien";
				colvarIdHocVien.DataType = DbType.Guid;
				colvarIdHocVien.MaxLength = 0;
				colvarIdHocVien.AutoIncrement = false;
				colvarIdHocVien.IsNullable = false;
				colvarIdHocVien.IsPrimaryKey = false;
				colvarIdHocVien.IsForeignKey = true;
				colvarIdHocVien.IsReadOnly = false;
				colvarIdHocVien.DefaultSetting = @"";
				
					colvarIdHocVien.ForeignKeyTableName = "HocVien";
				schema.Columns.Add(colvarIdHocVien);
				
				TableSchema.TableColumn colvarIdLop = new TableSchema.TableColumn(schema);
				colvarIdLop.ColumnName = "IdLop";
				colvarIdLop.DataType = DbType.Guid;
				colvarIdLop.MaxLength = 0;
				colvarIdLop.AutoIncrement = false;
				colvarIdLop.IsNullable = false;
				colvarIdLop.IsPrimaryKey = false;
				colvarIdLop.IsForeignKey = true;
				colvarIdLop.IsReadOnly = false;
				colvarIdLop.DefaultSetting = @"";
				
					colvarIdLop.ForeignKeyTableName = "Lop";
				schema.Columns.Add(colvarIdLop);
				
				TableSchema.TableColumn colvarGhiChu = new TableSchema.TableColumn(schema);
				colvarGhiChu.ColumnName = "GhiChu";
				colvarGhiChu.DataType = DbType.String;
				colvarGhiChu.MaxLength = 1073741823;
				colvarGhiChu.AutoIncrement = false;
				colvarGhiChu.IsNullable = true;
				colvarGhiChu.IsPrimaryKey = false;
				colvarGhiChu.IsForeignKey = false;
				colvarGhiChu.IsReadOnly = false;
				colvarGhiChu.DefaultSetting = @"";
				colvarGhiChu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGhiChu);
				
				TableSchema.TableColumn colvarTrangThai = new TableSchema.TableColumn(schema);
				colvarTrangThai.ColumnName = "TrangThai";
				colvarTrangThai.DataType = DbType.String;
				colvarTrangThai.MaxLength = 20;
				colvarTrangThai.AutoIncrement = false;
				colvarTrangThai.IsNullable = true;
				colvarTrangThai.IsPrimaryKey = false;
				colvarTrangThai.IsForeignKey = false;
				colvarTrangThai.IsReadOnly = false;
				colvarTrangThai.DefaultSetting = @"";
				colvarTrangThai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrangThai);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["QLSUN"].AddSchema("NhapHoc",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdNhapHoc")]
		[Bindable(true)]
		public Guid IdNhapHoc 
		{
			get { return GetColumnValue<Guid>(Columns.IdNhapHoc); }
			set { SetColumnValue(Columns.IdNhapHoc, value); }
		}
		  
		[XmlAttribute("IdHocVien")]
		[Bindable(true)]
		public Guid IdHocVien 
		{
			get { return GetColumnValue<Guid>(Columns.IdHocVien); }
			set { SetColumnValue(Columns.IdHocVien, value); }
		}
		  
		[XmlAttribute("IdLop")]
		[Bindable(true)]
		public Guid IdLop 
		{
			get { return GetColumnValue<Guid>(Columns.IdLop); }
			set { SetColumnValue(Columns.IdLop, value); }
		}
		  
		[XmlAttribute("GhiChu")]
		[Bindable(true)]
		public string GhiChu 
		{
			get { return GetColumnValue<string>(Columns.GhiChu); }
			set { SetColumnValue(Columns.GhiChu, value); }
		}
		  
		[XmlAttribute("TrangThai")]
		[Bindable(true)]
		public string TrangThai 
		{
			get { return GetColumnValue<string>(Columns.TrangThai); }
			set { SetColumnValue(Columns.TrangThai, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		public Public.DiemDanhCollection DiemDanhRecords()
		{
			return new Public.DiemDanhCollection().Where(DiemDanh.Columns.IdNhapHoc, IdNhapHoc).Load();
		}
		public Public.HocPhiCollection HocPhiRecords()
		{
			return new Public.HocPhiCollection().Where(HocPhi.Columns.IdNhapHoc, IdNhapHoc).Load();
		}
		public Public.KetQuaHocTapCollection KetQuaHocTapRecords()
		{
			return new Public.KetQuaHocTapCollection().Where(KetQuaHocTap.Columns.IdNhapHoc, IdNhapHoc).Load();
		}
		#endregion
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a HocVien ActiveRecord object related to this NhapHoc
		/// 
		/// </summary>
		public Public.HocVien HocVien
		{
			get { return Public.HocVien.FetchByID(this.IdHocVien); }
			set { SetColumnValue("IdHocVien", value.IdHocVien); }
		}
		
		
		/// <summary>
		/// Returns a Lop ActiveRecord object related to this NhapHoc
		/// 
		/// </summary>
		public Public.Lop Lop
		{
			get { return Public.Lop.FetchByID(this.IdLop); }
			set { SetColumnValue("IdLop", value.IdLop); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdNhapHoc,Guid varIdHocVien,Guid varIdLop,string varGhiChu,string varTrangThai)
		{
			NhapHoc item = new NhapHoc();
			
			item.IdNhapHoc = varIdNhapHoc;
			
			item.IdHocVien = varIdHocVien;
			
			item.IdLop = varIdLop;
			
			item.GhiChu = varGhiChu;
			
			item.TrangThai = varTrangThai;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdNhapHoc,Guid varIdHocVien,Guid varIdLop,string varGhiChu,string varTrangThai)
		{
			NhapHoc item = new NhapHoc();
			
				item.IdNhapHoc = varIdNhapHoc;
			
				item.IdHocVien = varIdHocVien;
			
				item.IdLop = varIdLop;
			
				item.GhiChu = varGhiChu;
			
				item.TrangThai = varTrangThai;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdNhapHocColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdHocVienColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IdLopColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn GhiChuColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn TrangThaiColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdNhapHoc = @"IdNhapHoc";
			 public static string IdHocVien = @"IdHocVien";
			 public static string IdLop = @"IdLop";
			 public static string GhiChu = @"GhiChu";
			 public static string TrangThai = @"TrangThai";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
}
        #endregion
	}
}
