using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    public partial class NhapHoc
    {
        public string HoTen { get; set; }
        public DateTime NamSinh { get; set; }
        public string FaceBook { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string TenLop { get; set; }
        public string GioiTinh { get; set; }
        public decimal HocPhiLop { get; set; }
        public Int32 TongHV { get; set; }

    }

    /// <summary>
    /// Controller class for NhapHoc
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class NhapHocController
    {
        // Preload our schema..
        NhapHoc thisSchemaLoad = new NhapHoc();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public NhapHocCollection FetchAll()
        {
            NhapHocCollection coll = new NhapHocCollection();
            Query qry = new Query(NhapHoc.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public NhapHocCollection FetchByID(object IdNhapHoc)
        {
            NhapHocCollection coll = new NhapHocCollection().Where("IdNhapHoc", IdNhapHoc).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public NhapHocCollection FetchByQuery(Query qry)
        {
            NhapHocCollection coll = new NhapHocCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdNhapHoc)
        {
            return (NhapHoc.Delete(IdNhapHoc) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdNhapHoc)
        {
            return (NhapHoc.Destroy(IdNhapHoc) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public NhapHoc Insert(NhapHoc item)
	    {
		    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public NhapHoc Update(NhapHoc item)
	    {
		    
	        item.Save(UserName);
            return item;
	    }
    }
}
