using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Public
{
    
    /// <summary>
    /// Controller class for PhongHoc
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class PhongHocController
    {
        // Preload our schema..
        PhongHoc thisSchemaLoad = new PhongHoc();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public PhongHocCollection FetchAll()
        {
            PhongHocCollection coll = new PhongHocCollection();
            Query qry = new Query(PhongHoc.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public PhongHocCollection FetchByID(object IdPhongHoc)
        {
            PhongHocCollection coll = new PhongHocCollection().Where("IdPhongHoc", IdPhongHoc).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public PhongHocCollection FetchByQuery(Query qry)
        {
            PhongHocCollection coll = new PhongHocCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdPhongHoc)
        {
            return (PhongHoc.Delete(IdPhongHoc) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdPhongHoc)
        {
            return (PhongHoc.Destroy(IdPhongHoc) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public PhongHoc Insert(PhongHoc item)
	    {
		    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public PhongHoc Update(PhongHoc item)
	    {
		    
	        item.Save(UserName);
            return item;
	    }
    }
}
